ca.count <- pp$ca(l,T)
co.count <- pp$co(l,T)
ps <- cc2ps2(tau,pp$mat, ca.count,co.count)
tests <- bhq(ps,0.2)
print(length(tests$hs.rejected))
print(sum(1-alts[tests$hs.rejected]))
print(sum(1-alts[tests$hs.rejected])/length(tests$hs.rejected))
ps.i <- cc2ps2(tau, ppi$mat.i, ca.count,co.count)
zs.i <- cc2ps2(tau, ppi$mat.i, ca.count,co.count,T)
tests.i <- bhq(ps.i[-taglist],0.2)
print(length(tests.i$hs.rejected))
print(sum(!alts2[tests.i$hs.rejected]))
print(sum(!alts2[tests.i$hs.rejected])/length(tests.i$hs.rejected))
n.v <- floor((m-length(taglist))*1)
inds.v <- sample((1:m)[-taglist],n.v)
ps.val <- cc2ps2(tau,pp$mat,pp$ca(l.val,T),pp$co(l.val,T))
val.res <- bhq(ps.val[inds.v],.5)
null.samp <- inds.v[val.res$hs.accepted]
p.est <- zs.i[null.samp]
phats <- finvert(-p.est,-zs.i,0.1)
ourtest <- bhq(phats[-taglist],0.2)
print(length(ourtest$hs.rejected))
print(sum(!alts2[ourtest$hs.rejected]))
print(sum(!alts2[ourtest$hs.rejected])/length(ourtest$hs.rejected))
